version: '2'

services:
  web:
    image: nginx:latest
    hostname: selfservicepassword.example.com
    volumes_from:
      - php
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
  php:
    image: moss/selfservicepassword
    hostname: selfservicepassword.example.com
    env_file: .env
